language: php

php:
  - 7.0
  - 7.1

sudo: false

addons:
  apt:
    packages:
      - parallel

env:
  - NODE_VERSION="6.0"

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install $NODE_VERSION
  - composer self-update
  - composer --version
  - composer install
  - npm install

script:
  # Run full test suite and linting of the code base
  - npm run build:suite